version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:               # 处理器
    console:            # 控制台输出
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    debug_file_handler:  # info 文件输出
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: logs/debug.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    info_file_handler:  # info 文件输出
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: logs/info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    error_file_handler: # error 文件输出
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: logs/errors.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers:      # 记录器
    my_module:
            level: ERROR
            handlers: [info_file_handler]
            propagate: no
root:
    level: INFO #基本记录等级
    handlers: [console,debug_file_handler,info_file_handler,error_file_handler]